travis:
  secure:
    BINSTAR_TOKEN: Uz2GAlsLFwUmUtOOcYuw39mVlofyJWSCpbAt+ssx7PtsG41zUcS1Y6rsZ2s3ATsCwP+KBpjdWgwPwVdzARNoZ2pvYXkG3xzfEK0XnnegtPT7bN0Z/PKwNxvG3YMxeLVE6PkhK+bslhDFO+KFgNrII8gk5Qq4cjLPgX22X3zM7pRhF3DuALNYj6CPOnQn+I/LCL5oRgzcVs95c9q0RMtHR5urOHp9/an0FIa95c2DvxHFU10BPWAfTt8e1eVEYEUzgUeckc7gYoky09HXOBWB4sa4r5ECklh/uRV/pCC+xVmq17cFJp06qyjMhUCu7VAIpmb+mS9PyLhzPSnsohMe/P1YiVxaVZ+za7vRxEVDza6JyJFx2ZXEj59zmc5bgOfnT3/eX1qU1RYUxuGPgWeYPxHSFSJIPWypSdFDe8RbkJcCiNZV/Mrhd5UYP/MHDDrBK70LqH5QDhzXshbtumL4beaZLIrWr9FcpV1Wi5MSe+JTmKMVOx7tVMaNSdtJoMuqR4fgNXPYe32RLW/LGGbkLJUWxCAz2MJTw9TOGTC4Sazs6Xtc+gvS+HtOhxO3KPhlUAliMnF/Hamv8/qVuobD2SrpQ3ZmZVornPWTIIsRdgRr8wAdMtVMAg4Kol40gTEzT9QlyFyuTAnY3bp6j2Vi6cV4v18Uva0c9OSmR7jegxo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
