travis:
  secure:
    BINSTAR_TOKEN: O1kZojlRk8I2kwK/VKNSN4Bg16y/uchXKW+VPTr5CfUmQcmKvh7disODfUfjOjMyLGbiajP2616uwzVAcZqO0OYoRQOyd9B1KIVi2vJfzKTxoaVyxyk+Ub0uHHuzL71q5gXaY2PJAHgObou8nWOIiXzqW1bOM8GM/7dg0KTw3aQi3vkOwRcDmao5NCGfCgxuROphnsIcguWyg1MFGvI7CtIQ2LBnqqJ/YBjrnAuMGZmokFs5cfn4fAEFeYa3XexyOZtj70C9fVa30soSbR8bO0z9Jl/X2WvA56eLpe4XiAj4MsrehqZEJnp2bXCliCLIGAy66fgjfDu9OCsuX4muoKmfWDi3+Wdm7lwCBB59MbW8FREbP9KVWAtO8TqP2JcTm/zQEZ5QRNoJWSvsqbW1pKrXLLf4+oOktH3W/usnTVxIuGkFWv0ahSS7xZPPJD3G+f26SGRdx/1xSFXQuU15ZkEZBAhOqt1P/vAq4rB3hnw3R/O6j8KjKVVPcv5TYWQ6MqywXgzmnZ5pSL0btZZi/P+FTMuz3Es+GbszcE0JrMwxZohvfVZiZE+aIyhgX5vnqy/VEEVrgaEHpAEa2GArglhxZQEHdh+G2MwDyFkSqNkv/zw0iMt4KHZUUR+wA8UwjcGKRU/uH9SQnjemVTII8MQiOweHKr5kjYoLzp1IO+A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
